### ISSUE TITLE
Mejora Servicios SINAI

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinai#1]
El servicio Consulta Antecedente CENAT, se le agregó 4 campos, los que figuran en rojo en el documento, 
no se exactamente si son esos los datos que espera recibir Raul,pero bueno, cuando Lean los agregue avisame y hacemos una pruebas para que salga todo ok. 

Por otro lado, el servicio de novedades,no hay que hacerle ca

[SINAI - Servicio Web de Consulta de Antecedentes para CENAT.docx](https://github.com/leoimoli/Sinai/files/326459/SINAI.-.Servicio.Web.de.Consulta.de.Antecedentes.para.CENAT.docx)
[SINAI - Servicio Web de Novedades de Inhabilitados sin Inhab prciales.docx](https://github.com/leoimoli/Sinai/files/326460/SINAI.-.Servicio.Web.de.Novedades.de.Inhabilitados.sin.Inhab.prciales.docx)

mbios, solo testearlo con Raul.

Trabajar en la Version de testing.

**Comment by leodimonio** [comment]
finalizado en version 1.13.8
